WEIGHT_CLASSES:
  125: Flyweight
  135: Bantamweight
  145: Featherweight
  155: Lightweight
  170: Welterweight
  185: Middleweight
  205: Light Heavyweight
  265: Heavyweight

NEW_ORDER_1:
  - event_country
  - event_date
  - is_interim_fight
  - is_title_fight
  - is_women_fight
  - weight_class
  - fight_lasted
  - method
  - referee
  - details
  - f1_name
  - f2_name
  - f1_odds
  - f2_odds
  - f1_height
  - f2_height
  - f1_stance
  - f2_stance
  - f1_dob
  - f2_dob
  - f1_reach
  - f2_reach
  - f1_total_knock_downs
  - f2_total_knock_downs
  - f1_total_signif_str
  - f2_total_signif_str
  - f1_total_total_str
  - f2_total_total_str
  - f1_total_take_downs
  - f2_total_take_downs
  - f1_total_sub_atts
  - f2_total_sub_atts
  - f1_total_rev
  - f2_total_rev
  - f1_total_ctrl
  - f2_total_ctrl
  - f1_total_head
  - f2_total_head
  - f1_total_body
  - f2_total_body
  - f1_total_leg
  - f2_total_leg
  - f1_total_distance
  - f2_total_distance
  - f1_total_clinch
  - f2_total_clinch
  - f1_total_ground
  - f2_total_ground
  - target

COLUMNS_TO_REMOVE:
  - f1_total_knock_downs
  - f2_total_knock_downs
  - f1_total_signif_str
  - f2_total_signif_str
  - f1_total_total_str
  - f2_total_total_str
  - f1_total_take_downs
  - f2_total_take_downs
  - f1_total_sub_atts
  - f2_total_sub_atts
  - f1_total_rev
  - f2_total_rev
  - f1_total_ctrl
  - f2_total_ctrl
  - f1_total_head
  - f2_total_head
  - f1_total_body
  - f2_total_body
  - f1_total_leg
  - f2_total_leg
  - f1_total_distance
  - f2_total_distance
  - f1_total_clinch
  - f2_total_clinch
  - f1_total_ground
  - f2_total_ground

NEW_ORDER_2:
  - event_country
  - event_date
  - is_interim_fight
  - is_title_fight
  - is_women_fight
  - weight_class
  - fight_lasted
  - method
  - referee
  - details
  - f1_name
  - f2_name
  - f1_odds
  - f2_odds
  - f1_height
  - f2_height
  - f1_stance
  - f2_stance
  - f1_dob
  - f2_dob
  - f1_reach
  - f2_reach
  - f1_knock_downs
  - f2_knock_downs
  - f1_sig_str_lan
  - f2_sig_str_lan
  - f1_sig_str_thr
  - f2_sig_str_thr
  - f1_tot_str_lan
  - f2_tot_str_lan
  - f1_tot_str_thr
  - f2_tot_str_thr
  - f1_take_downs_lan
  - f2_take_downs_lan
  - f1_take_downs_thr
  - f2_take_downs_thr
  - f1_sub_atts
  - f2_sub_atts
  - f1_rev
  - f2_rev
  - f1_ctrl
  - f2_ctrl
  - f1_head_str_lan
  - f2_head_str_lan
  - f1_head_str_thr
  - f2_head_str_thr
  - f1_body_str_lan
  - f2_body_str_lan
  - f1_body_str_thr
  - f2_body_str_thr
  - f1_leg_str_lan
  - f2_leg_str_lan
  - f1_leg_str_thr
  - f2_leg_str_thr
  - f1_dist_str_lan
  - f2_dist_str_lan
  - f1_dist_str_thr
  - f2_dist_str_thr
  - f1_clin_str_lan
  - f2_clin_str_lan
  - f1_clin_str_thr
  - f2_clin_str_thr
  - f1_ground_str_lan
  - f2_ground_str_lan
  - f1_ground_str_thr
  - f2_ground_str_thr
  - target
  